### ISSUE TITLE
molden_manage.f90 is not included

### ISSUE THREAD

**Issue by panwangzhou** [jcerezochem/fcc_tools#1]
When I install fcc_tools with make command, the following errors occurred:
make[1]: *** No rule to make target '../modules/molden_manage.f90', needed by '../modules/molden_manage.o'.  Stop.
It seems that the molden_manage.f90 is not included in the src. Thanks.

**Comment by jcerezochem** [comment]
Yes, you are right, it was not included in the repo. Moreover, there was a missing line in src/generators/Makefile.am. Should be solved from commit 1a3700e. I've checked cloning now the repo and it works. Thanks for reporting!
