### ISSUE TITLE
How to generate fcc_analyzer_PyQt5 input file?

### ISSUE THREAD

**Issue by lizhiq16** [jcerezochem/fcc_tools#3]
I have used the FCclasses3 to do EM/OPA, but I didn't get the " fort.21/Assigments.dat (assignments) and either fort.22/Bin_Spectrum.dat" for fcc_analyzer after finished the calculation. 
So how to generate fcc_analyzer_PyQt5 input file?

**Comment by jcerezochem** [comment]
`fcc_analyzer_PyQt5` uses the output generated after a successful run of a TI calculation (`METHOD = TI` in the input file) with [FCclasses](http://www.iccom.cnr.it/en/fcclasses/). It supports OPA, EMI, ECD,  CPL, TPA and TPCD.
